"""MCP server exposing Sonarr's v3 REST API (OpenAPI 3.0.0) as tools.

Full coverage of every JSON-producing endpoint under /api/v3 plus GET /ping
(binary/text endpoints - media covers and raw log files - are excluded), but
exposed as ~15 resource-scoped *portmanteau* tools instead of one tool per
endpoint. Each portmanteau tool (e.g. sonarr_queue, sonarr_media_library)
takes an `operation` enum plus an `arguments` dict; see AGENTS.md for the
rationale (a 200+-tool server blows the MCP context budget on session start).

The vendored spec at tests/data/sonarr_openapi.json (develop HEAD
e7caf8fbaa8e7b9dff48ce26b476ebcad7fd7324) still generates one async function
per endpoint into `_TOOL_REGISTRY` - keep it in sync with the spec (see
AGENTS.md). Those functions are no longer registered as individual MCP
tools; `_GROUPS` below buckets them by resource, and `_register_group` wraps
each bucket in a single dispatching tool that calls the right function by
name. Nothing about the endpoint functions themselves changes - grouping is
purely a registration-time concern.

Auth is the X-Api-Key header, generated in Sonarr > Settings > General >
Security. A group tool is marked readOnlyHint=True only when every operation
in it is a GET; mixed groups carry no hints (writes still get a `WRITE:` /
`DESTRUCTIVE:` note in their operation's doc line). Bodies are passed as
opaque dicts/lists. build_client points at the origin with no path suffix so
httpx joins the fully-qualified paths (including /ping) correctly.
"""

import inspect
import os
import sys
from typing import Any, Literal
from urllib.parse import quote

import httpx
from fastmcp import FastMCP
from fastmcp.exceptions import ToolError
from fastmcp.tools import Tool
from mcp.types import ToolAnnotations

READONLY = ToolAnnotations(readOnlyHint=True)
WRITE = ToolAnnotations(readOnlyHint=False, destructiveHint=False)
DESTRUCTIVE = ToolAnnotations(readOnlyHint=False, destructiveHint=True)

# Sonarr responses are plain JSON. `dict[str, Any]` (not bare `Any`) matters
# here: FastMCP needs a concrete schema to build MCP structured content, and
# skips that step entirely for an `Any` return type -- which silently makes
# Client.call_tool's `.data` come back None for any tool returning a JSON array
# (sonarr_list_series and friends). Verified against fastmcp 3.4.7.
JSONObj = dict[str, Any]
JSONVal = JSONObj | list[Any]

mcp = FastMCP("sonarr-mcp")

_client: httpx.AsyncClient | None = None


def build_client(
    base_url: str, api_key: str | None, transport: httpx.BaseTransport | None = None
) -> httpx.AsyncClient:
    """Client pinned to the origin (no path suffix) so registered full paths
    like /api/v3/series and /ping both resolve correctly via httpx base join."""
    headers = {"X-Api-Key": api_key} if api_key else {}
    return httpx.AsyncClient(base_url=f"{base_url.rstrip('/')}", headers=headers, transport=transport)


async def _req(
    method: str,
    path: str,
    params: dict[str, Any] | None = None,
    json_body: JSONVal | None = None,
) -> JSONVal:
    assert _client is not None, "client not configured"
    r = await _client.request(method, path, params=params, json=json_body)
    if r.status_code >= 400:
        try:
            msg = r.json().get("message", r.text)
        except ValueError:
            msg = r.text
        raise ToolError(f"Sonarr API {r.status_code}: {msg}")
    if not r.text:
        return {}
    return r.json()


def _omit(params: dict[str, Any]) -> dict[str, Any]:
    """Drop keys whose values are empty/None so the API's defaults apply."""
    return {k: v for k, v in params.items() if v not in ("", None)}


# Resource groups for portmanteau registration. Every _TOOL_REGISTRY name
# must appear in exactly one group - see test_all_registry_names_grouped.
_GROUPS: dict[str, tuple[str, ...]] = {
    "sonarr_profiles_formats": (
        'sonarr_bulk_delete_customformat',
        'sonarr_bulk_update_customformat',
        'sonarr_create_autotagging',
        'sonarr_create_customfilter',
        'sonarr_create_customformat',
        'sonarr_create_delayprofile',
        'sonarr_create_languageprofile',
        'sonarr_create_qualityprofile',
        'sonarr_create_releaseprofile',
        'sonarr_delete_autotagging',
        'sonarr_delete_customfilter',
        'sonarr_delete_customformat',
        'sonarr_delete_delayprofile',
        'sonarr_delete_languageprofile',
        'sonarr_delete_qualityprofile',
        'sonarr_delete_releaseprofile',
        'sonarr_get_autotagging',
        'sonarr_get_customfilter',
        'sonarr_get_customformat',
        'sonarr_get_delayprofile',
        'sonarr_get_language',
        'sonarr_get_languageprofile',
        'sonarr_get_qualitydefinition',
        'sonarr_get_qualitydefinition_limits',
        'sonarr_get_qualityprofile',
        'sonarr_get_releaseprofile',
        'sonarr_list_autotagging',
        'sonarr_list_autotagging_schema',
        'sonarr_list_customfilter',
        'sonarr_list_customformat',
        'sonarr_list_customformat_schema',
        'sonarr_list_delayprofile',
        'sonarr_list_language',
        'sonarr_list_languageprofile',
        'sonarr_list_languageprofile_schema',
        'sonarr_list_qualitydefinition',
        'sonarr_list_qualityprofile',
        'sonarr_list_qualityprofile_schema',
        'sonarr_list_releaseprofile',
        'sonarr_reorder_delayprofile',
        'sonarr_update_autotagging',
        'sonarr_update_customfilter',
        'sonarr_update_customformat',
        'sonarr_update_delayprofile',
        'sonarr_update_languageprofile',
        'sonarr_update_quality_definitions',
        'sonarr_update_qualitydefinition',
        'sonarr_update_qualityprofile',
        'sonarr_update_releaseprofile',
    ),
    "sonarr_config": (
        'sonarr_get_config_downloadclient',
        'sonarr_get_config_downloadclient_by_id',
        'sonarr_get_config_host',
        'sonarr_get_config_host_by_id',
        'sonarr_get_config_importlist',
        'sonarr_get_config_importlist_by_id',
        'sonarr_get_config_indexer',
        'sonarr_get_config_indexer_by_id',
        'sonarr_get_config_mediamanagement',
        'sonarr_get_config_mediamanagement_by_id',
        'sonarr_get_config_naming',
        'sonarr_get_config_naming_by_id',
        'sonarr_get_config_ui',
        'sonarr_get_config_ui_by_id',
        'sonarr_get_localization',
        'sonarr_get_localization_language',
        'sonarr_list_config_naming_examples',
        'sonarr_list_localization',
        'sonarr_list_update',
        'sonarr_update_config_downloadclient',
        'sonarr_update_config_host',
        'sonarr_update_config_importlist',
        'sonarr_update_config_indexer',
        'sonarr_update_config_mediamanagement',
        'sonarr_update_config_naming',
        'sonarr_update_config_ui',
    ),
    "sonarr_media_library": (
        'sonarr_add_series',
        'sonarr_bulk_delete_episodefile',
        'sonarr_bulk_delete_series',
        'sonarr_bulk_edit_episodefiles',
        'sonarr_bulk_update_episodefile',
        'sonarr_bulk_update_series',
        'sonarr_commit_manual_import',
        'sonarr_delete_episodefile',
        'sonarr_delete_series',
        'sonarr_get_episode',
        'sonarr_get_episodefile',
        'sonarr_get_parse',
        'sonarr_get_rename',
        'sonarr_get_series',
        'sonarr_get_series_folder',
        'sonarr_import_series',
        'sonarr_list_episode',
        'sonarr_list_episodefile',
        'sonarr_list_manualimport',
        'sonarr_list_series',
        'sonarr_lookup_series',
        'sonarr_monitor_episode',
        'sonarr_update_episode',
        'sonarr_update_episodefile',
        'sonarr_update_season_pass',
        'sonarr_update_series',
    ),
    "sonarr_system_commands": (
        'sonarr_delete_command',
        'sonarr_delete_system_backup',
        'sonarr_get_command',
        'sonarr_get_health',
        'sonarr_get_system_routes',
        'sonarr_get_system_routes_duplicate',
        'sonarr_get_system_status',
        'sonarr_get_system_task',
        'sonarr_get_system_task_by_id',
        'sonarr_list_command',
        'sonarr_list_log',
        'sonarr_list_log_file',
        'sonarr_list_log_file_update',
        'sonarr_list_system_backup',
        'sonarr_ping',
        'sonarr_restart_sonarr',
        'sonarr_restore_backup',
        'sonarr_restore_backup_upload',
        'sonarr_run_command',
        'sonarr_shutdown_sonarr',
    ),
    "sonarr_import_lists": (
        'sonarr_create_importlist',
        'sonarr_create_importlist_action',
        'sonarr_create_importlist_test',
        'sonarr_create_importlist_testall',
        'sonarr_create_importlistexclusion',
        'sonarr_delete_importlist',
        'sonarr_delete_importlist_bulk',
        'sonarr_delete_importlistexclusion',
        'sonarr_delete_importlistexclusion_bulk',
        'sonarr_get_importlist',
        'sonarr_get_importlistexclusion',
        'sonarr_list_importlist',
        'sonarr_list_importlist_schema',
        'sonarr_list_importlistexclusion',
        'sonarr_list_importlistexclusion_paged',
        'sonarr_update_importlist',
        'sonarr_update_importlist_bulk',
        'sonarr_update_importlistexclusion',
    ),
    "sonarr_notifications_metadata": (
        'sonarr_create_metadata',
        'sonarr_create_metadata_action',
        'sonarr_create_metadata_test',
        'sonarr_create_metadata_testall',
        'sonarr_create_notification',
        'sonarr_create_notification_action',
        'sonarr_create_notification_test',
        'sonarr_create_notification_testall',
        'sonarr_delete_metadata',
        'sonarr_delete_notification',
        'sonarr_get_metadata',
        'sonarr_get_notification',
        'sonarr_list_metadata',
        'sonarr_list_metadata_schema',
        'sonarr_list_notification',
        'sonarr_list_notification_schema',
        'sonarr_update_metadata',
        'sonarr_update_notification',
    ),
    "sonarr_download_clients": (
        'sonarr_create_downloadclient',
        'sonarr_create_downloadclient_action',
        'sonarr_create_downloadclient_test',
        'sonarr_create_downloadclient_testall',
        'sonarr_create_remotepathmapping',
        'sonarr_delete_downloadclient',
        'sonarr_delete_downloadclient_bulk',
        'sonarr_delete_remotepathmapping',
        'sonarr_get_downloadclient',
        'sonarr_get_remotepathmapping',
        'sonarr_list_downloadclient',
        'sonarr_list_downloadclient_schema',
        'sonarr_list_remotepathmapping',
        'sonarr_update_downloadclient',
        'sonarr_update_downloadclient_bulk',
        'sonarr_update_remotepathmapping',
    ),
    "sonarr_indexers": (
        'sonarr_create_indexer',
        'sonarr_create_indexer_action',
        'sonarr_create_indexer_test',
        'sonarr_create_indexer_testall',
        'sonarr_delete_indexer',
        'sonarr_delete_indexer_bulk',
        'sonarr_get_indexer',
        'sonarr_list_indexer',
        'sonarr_list_indexer_schema',
        'sonarr_update_indexer',
        'sonarr_update_indexer_bulk',
    ),
    "sonarr_storage": (
        'sonarr_create_rootfolder',
        'sonarr_delete_rootfolder',
        'sonarr_get_diskspace',
        'sonarr_get_rootfolder',
        'sonarr_list_filesystem',
        'sonarr_list_filesystem_mediafiles',
        'sonarr_list_filesystem_type',
        'sonarr_list_rootfolder',
    ),
    "sonarr_history_blocklist": (
        'sonarr_bulk_delete_blocklist',
        'sonarr_delete_blocklist',
        'sonarr_list_blocklist',
        'sonarr_list_history',
        'sonarr_list_history_series',
        'sonarr_list_history_since',
        'sonarr_mark_history_item_failed',
    ),
    "sonarr_queue": (
        'sonarr_bulk_delete_queue',
        'sonarr_delete_queue',
        'sonarr_get_queue_details',
        'sonarr_get_queue_status',
        'sonarr_grab_queue_bulk',
        'sonarr_grab_queue_item',
        'sonarr_list_queue',
    ),
    "sonarr_tags": (
        'sonarr_create_tag',
        'sonarr_delete_tag',
        'sonarr_get_tag',
        'sonarr_get_tag_detail',
        'sonarr_list_tag',
        'sonarr_list_tag_detail',
        'sonarr_update_tag',
    ),
    "sonarr_release_search": (
        'sonarr_get_indexerflag',
        'sonarr_list_release',
        'sonarr_push_release',
        'sonarr_search_releases',
    ),
    "sonarr_wanted": (
        'sonarr_get_wanted_cutoff',
        'sonarr_get_wanted_missing',
        'sonarr_list_wanted_cutoff',
        'sonarr_list_wanted_missing',
    ),
    "sonarr_calendar": (
        'sonarr_get_calendar',
        'sonarr_list_calendar',
    ),
}


_TOOL_REGISTRY: list[dict[str, Any]] = [
 {'name': 'sonarr_list_autotagging',
  'method': 'GET',
  'path': '/api/v3/autotagging',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List auto tagging rules.',
 },
 {'name': 'sonarr_create_autotagging',
  'method': 'POST',
  'path': '/api/v3/autotagging',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create auto tagging rules. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_autotagging_schema',
  'method': 'GET',
  'path': '/api/v3/autotagging/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the auto tagging rules schema (available fields/options).',
 },
 {'name': 'sonarr_delete_autotagging',
  'method': 'DELETE',
  'path': '/api/v3/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete auto tagging rules. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_autotagging',
  'method': 'GET',
  'path': '/api/v3/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single auto tagging rules by id.',
 },
 {'name': 'sonarr_update_autotagging',
  'method': 'PUT',
  'path': '/api/v3/autotagging/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update auto tagging rules. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_blocklist',
  'method': 'GET',
  'path': '/api/v3/blocklist',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
          {'name': 'series_ids', 'wire': 'seriesIds', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'protocols', 'wire': 'protocols', 'type': 'list[Any]', 'default': 'None'},
         ],
  'bk': 'none',
  'doc': 'List blocklisted releases. Query params: sort_key, sort_direction.',
 },
 {'name': 'sonarr_bulk_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v3/blocklist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete blocklist bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v3/blocklist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete blocklisted releases. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_list_calendar',
  'method': 'GET',
  'path': '/api/v3/calendar',
  'pp': [],
  'qp': [
          {'name': 'start', 'wire': 'start', 'type': 'str', 'default': '""'},
          {'name': 'end', 'wire': 'end', 'type': 'str', 'default': '""'},
          {'name': 'unmonitored', 'wire': 'unmonitored', 'type': 'bool', 'default': 'False'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode_file', 'wire': 'includeEpisodeFile', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode_images', 'wire': 'includeEpisodeImages', 'type': 'bool', 'default': 'False'},
          {'name': 'tags', 'wire': 'tags', 'type': 'str', 'default': "''"},
         ],
  'bk': 'none',
  'doc': 'List upcoming episode calendar. Query params: start, end, tags.',
 },
 {'name': 'sonarr_get_calendar',
  'method': 'GET',
  'path': '/api/v3/calendar/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single upcoming episode calendar by id.',
 },
 {'name': 'sonarr_list_command',
  'method': 'GET',
  'path': '/api/v3/command',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List queued/running commands.',
 },
 {'name': 'sonarr_run_command',
  'method': 'POST',
  'path': '/api/v3/command',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run a Sonarr command (body is a CommandResource with a `name`, e.g. RefreshSeries, SeriesSearch, DownloadedEpisodesScan). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_command',
  'method': 'DELETE',
  'path': '/api/v3/command/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete queued/running commands. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_command',
  'method': 'GET',
  'path': '/api/v3/command/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single queued/running commands by id.',
 },
 {'name': 'sonarr_get_config_downloadclient',
  'method': 'GET',
  'path': '/api/v3/config/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List download client config.',
 },
 {'name': 'sonarr_get_config_downloadclient_by_id',
  'method': 'GET',
  'path': '/api/v3/config/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single download client config by id.',
 },
 {'name': 'sonarr_update_config_downloadclient',
  'method': 'PUT',
  'path': '/api/v3/config/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update download client config. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_config_host',
  'method': 'GET',
  'path': '/api/v3/config/host',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List host config.',
 },
 {'name': 'sonarr_get_config_host_by_id',
  'method': 'GET',
  'path': '/api/v3/config/host/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single host config by id.',
 },
 {'name': 'sonarr_update_config_host',
  'method': 'PUT',
  'path': '/api/v3/config/host/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update host config. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_config_importlist',
  'method': 'GET',
  'path': '/api/v3/config/importlist',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import list config.',
 },
 {'name': 'sonarr_get_config_importlist_by_id',
  'method': 'GET',
  'path': '/api/v3/config/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import list config by id.',
 },
 {'name': 'sonarr_update_config_importlist',
  'method': 'PUT',
  'path': '/api/v3/config/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update import list config. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_config_indexer',
  'method': 'GET',
  'path': '/api/v3/config/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexer config.',
 },
 {'name': 'sonarr_get_config_indexer_by_id',
  'method': 'GET',
  'path': '/api/v3/config/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single indexer config by id.',
 },
 {'name': 'sonarr_update_config_indexer',
  'method': 'PUT',
  'path': '/api/v3/config/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update indexer config. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_config_mediamanagement',
  'method': 'GET',
  'path': '/api/v3/config/mediamanagement',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List media management config.',
 },
 {'name': 'sonarr_get_config_mediamanagement_by_id',
  'method': 'GET',
  'path': '/api/v3/config/mediamanagement/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single media management config by id.',
 },
 {'name': 'sonarr_update_config_mediamanagement',
  'method': 'PUT',
  'path': '/api/v3/config/mediamanagement/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update media management config. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_config_naming',
  'method': 'GET',
  'path': '/api/v3/config/naming',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List naming.',
 },
 {'name': 'sonarr_list_config_naming_examples',
  'method': 'GET',
  'path': '/api/v3/config/naming/examples',
  'pp': [],
  'qp': [
          {'name': 'rename_episodes', 'wire': 'renameEpisodes', 'type': 'bool', 'default': 'None'},
          {'name': 'replace_illegal_characters', 'wire': 'replaceIllegalCharacters', 'type': 'bool', 'default': 'None'},
          {'name': 'colon_replacement_format', 'wire': 'colonReplacementFormat', 'type': 'int', 'default': 'None'},
          {'name': 'custom_colon_replacement_format', 'wire': 'customColonReplacementFormat', 'type': 'str', 'default': '""'},
          {'name': 'multi_episode_style', 'wire': 'multiEpisodeStyle', 'type': 'int', 'default': 'None'},
          {'name': 'standard_episode_format', 'wire': 'standardEpisodeFormat', 'type': 'str', 'default': '""'},
          {'name': 'daily_episode_format', 'wire': 'dailyEpisodeFormat', 'type': 'str', 'default': '""'},
          {'name': 'anime_episode_format', 'wire': 'animeEpisodeFormat', 'type': 'str', 'default': '""'},
          {'name': 'series_folder_format', 'wire': 'seriesFolderFormat', 'type': 'str', 'default': '""'},
          {'name': 'season_folder_format', 'wire': 'seasonFolderFormat', 'type': 'str', 'default': '""'},
          {'name': 'specials_folder_format', 'wire': 'specialsFolderFormat', 'type': 'str', 'default': '""'},
          {'name': 'id', 'wire': 'id', 'type': 'int', 'default': 'None'},
          {'name': 'resource_name', 'wire': 'resourceName', 'type': 'str', 'default': '""'},
         ],
  'bk': 'none',
  'doc': 'List naming examples. Query params: custom_colon_replacement_format, standard_episode_format, daily_episode_format, anime_episode_format, series_folder_format, season_folder_format, specials_folder_format, resource_name.',
 },
 {'name': 'sonarr_get_config_naming_by_id',
  'method': 'GET',
  'path': '/api/v3/config/naming/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single naming by id.',
 },
 {'name': 'sonarr_update_config_naming',
  'method': 'PUT',
  'path': '/api/v3/config/naming/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update naming. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_config_ui',
  'method': 'GET',
  'path': '/api/v3/config/ui',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List UI config.',
 },
 {'name': 'sonarr_get_config_ui_by_id',
  'method': 'GET',
  'path': '/api/v3/config/ui/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single UI config by id.',
 },
 {'name': 'sonarr_update_config_ui',
  'method': 'PUT',
  'path': '/api/v3/config/ui/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update UI config. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_customfilter',
  'method': 'GET',
  'path': '/api/v3/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List custom filters.',
 },
 {'name': 'sonarr_create_customfilter',
  'method': 'POST',
  'path': '/api/v3/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create custom filters. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_customfilter',
  'method': 'DELETE',
  'path': '/api/v3/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete custom filters. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_customfilter',
  'method': 'GET',
  'path': '/api/v3/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single custom filters by id.',
 },
 {'name': 'sonarr_update_customfilter',
  'method': 'PUT',
  'path': '/api/v3/customfilter/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update custom filters. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_customformat',
  'method': 'GET',
  'path': '/api/v3/customformat',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List custom formats.',
 },
 {'name': 'sonarr_create_customformat',
  'method': 'POST',
  'path': '/api/v3/customformat',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create custom formats. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_bulk_delete_customformat',
  'method': 'DELETE',
  'path': '/api/v3/customformat/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete customformat bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_bulk_update_customformat',
  'method': 'PUT',
  'path': '/api/v3/customformat/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update customformat bulk. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_customformat_schema',
  'method': 'GET',
  'path': '/api/v3/customformat/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the custom formats schema (available fields/options).',
 },
 {'name': 'sonarr_delete_customformat',
  'method': 'DELETE',
  'path': '/api/v3/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete custom formats. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_customformat',
  'method': 'GET',
  'path': '/api/v3/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single custom formats by id.',
 },
 {'name': 'sonarr_update_customformat',
  'method': 'PUT',
  'path': '/api/v3/customformat/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update custom formats. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_delayprofile',
  'method': 'GET',
  'path': '/api/v3/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List delay profiles.',
 },
 {'name': 'sonarr_create_delayprofile',
  'method': 'POST',
  'path': '/api/v3/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create delay profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_reorder_delayprofile',
  'method': 'PUT',
  'path': '/api/v3/delayprofile/reorder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'after', 'wire': 'after', 'type': 'int', 'default': 'None'},
         ],
  'bk': 'none',
  'doc': 'Update delayprofile reorder. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_delayprofile',
  'method': 'DELETE',
  'path': '/api/v3/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete delay profiles. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_delayprofile',
  'method': 'GET',
  'path': '/api/v3/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single delay profiles by id.',
 },
 {'name': 'sonarr_update_delayprofile',
  'method': 'PUT',
  'path': '/api/v3/delayprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update delay profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_diskspace',
  'method': 'GET',
  'path': '/api/v3/diskspace',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List diskspace.',
 },
 {'name': 'sonarr_list_downloadclient',
  'method': 'GET',
  'path': '/api/v3/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List download clients.',
 },
 {'name': 'sonarr_create_downloadclient',
  'method': 'POST',
  'path': '/api/v3/downloadclient',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create download clients. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_downloadclient_action',
  'method': 'POST',
  'path': '/api/v3/downloadclient/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create downloadclient action. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_downloadclient_bulk',
  'method': 'DELETE',
  'path': '/api/v3/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete downloadclient bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_update_downloadclient_bulk',
  'method': 'PUT',
  'path': '/api/v3/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update downloadclient bulk. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_downloadclient_schema',
  'method': 'GET',
  'path': '/api/v3/downloadclient/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the download clients schema (available fields/options).',
 },
 {'name': 'sonarr_create_downloadclient_test',
  'method': 'POST',
  'path': '/api/v3/downloadclient/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create downloadclient test. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_downloadclient_testall',
  'method': 'POST',
  'path': '/api/v3/downloadclient/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create downloadclient testall. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_downloadclient',
  'method': 'DELETE',
  'path': '/api/v3/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete download clients. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_downloadclient',
  'method': 'GET',
  'path': '/api/v3/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single download clients by id.',
 },
 {'name': 'sonarr_update_downloadclient',
  'method': 'PUT',
  'path': '/api/v3/downloadclient/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Update download clients. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_episode',
  'method': 'GET',
  'path': '/api/v3/episode',
  'pp': [],
  'qp': [
          {'name': 'series_id', 'wire': 'seriesId', 'type': 'int', 'default': 'None'},
          {'name': 'season_number', 'wire': 'seasonNumber', 'type': 'int', 'default': 'None'},
          {'name': 'episode_ids', 'wire': 'episodeIds', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'episode_file_id', 'wire': 'episodeFileId', 'type': 'int', 'default': 'None'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode_file', 'wire': 'includeEpisodeFile', 'type': 'bool', 'default': 'False'},
          {'name': 'include_images', 'wire': 'includeImages', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'List episodes.',
 },
 {'name': 'sonarr_monitor_episode',
  'method': 'PUT',
  'path': '/api/v3/episode/monitor',
  'pp': [],
  'qp': [
          {'name': 'include_images', 'wire': 'includeImages', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Monitor or unmonitor episodes (body is an EpisodeResource[] of id/monitored pairs). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_episode',
  'method': 'GET',
  'path': '/api/v3/episode/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single episodes by id.',
 },
 {'name': 'sonarr_update_episode',
  'method': 'PUT',
  'path': '/api/v3/episode/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update episodes. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_episodefile',
  'method': 'GET',
  'path': '/api/v3/episodefile',
  'pp': [],
  'qp': [
          {'name': 'series_id', 'wire': 'seriesId', 'type': 'int', 'default': 'None'},
          {'name': 'episode_file_ids', 'wire': 'episodeFileIds', 'type': 'list[Any]', 'default': 'None'},
         ],
  'bk': 'none',
  'doc': 'List episode files.',
 },
 {'name': 'sonarr_bulk_delete_episodefile',
  'method': 'DELETE',
  'path': '/api/v3/episodefile/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete episodefile bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_bulk_update_episodefile',
  'method': 'PUT',
  'path': '/api/v3/episodefile/bulk',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Update episodefile bulk. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_bulk_edit_episodefiles',
  'method': 'PUT',
  'path': '/api/v3/episodefile/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update episodefile editor. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_episodefile',
  'method': 'DELETE',
  'path': '/api/v3/episodefile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete episode files. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_episodefile',
  'method': 'GET',
  'path': '/api/v3/episodefile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single episode files by id.',
 },
 {'name': 'sonarr_update_episodefile',
  'method': 'PUT',
  'path': '/api/v3/episodefile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update episode files. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_filesystem',
  'method': 'GET',
  'path': '/api/v3/filesystem',
  'pp': [],
  'qp': [
          {'name': 'path', 'wire': 'path', 'type': 'str', 'default': '""'},
          {'name': 'include_files', 'wire': 'includeFiles', 'type': 'bool', 'default': 'False'},
          {'name': 'allow_folders_without_trailing_slashes', 'wire': 'allowFoldersWithoutTrailingSlashes', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'List server filesystem. Query params: path.',
 },
 {'name': 'sonarr_list_filesystem_mediafiles',
  'method': 'GET',
  'path': '/api/v3/filesystem/mediafiles',
  'pp': [],
  'qp': [
          {'name': 'path', 'wire': 'path', 'type': 'str', 'default': '""'},
         ],
  'bk': 'none',
  'doc': 'List media files. Query params: path.',
 },
 {'name': 'sonarr_list_filesystem_type',
  'method': 'GET',
  'path': '/api/v3/filesystem/type',
  'pp': [],
  'qp': [
          {'name': 'path', 'wire': 'path', 'type': 'str', 'default': '""'},
         ],
  'bk': 'none',
  'doc': 'List filesystem types. Query params: path.',
 },
 {'name': 'sonarr_get_health',
  'method': 'GET',
  'path': '/api/v3/health',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List health.',
 },
 {'name': 'sonarr_list_history',
  'method': 'GET',
  'path': '/api/v3/history',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'None'},
          {'name': 'include_episode', 'wire': 'includeEpisode', 'type': 'bool', 'default': 'None'},
          {'name': 'event_type', 'wire': 'eventType', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'episode_id', 'wire': 'episodeId', 'type': 'int', 'default': 'None'},
          {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': '""'},
          {'name': 'series_ids', 'wire': 'seriesIds', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'languages', 'wire': 'languages', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'quality', 'wire': 'quality', 'type': 'list[Any]', 'default': 'None'},
         ],
  'bk': 'none',
  'doc': 'List download/import history. Query params: sort_key, sort_direction, download_id.',
 },
 {'name': 'sonarr_mark_history_item_failed',
  'method': 'POST',
  'path': '/api/v3/history/failed/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Mark a history item as failed (blocklists the release by default). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_history_series',
  'method': 'GET',
  'path': '/api/v3/history/series',
  'pp': [],
  'qp': [
          {'name': 'series_id', 'wire': 'seriesId', 'type': 'int', 'default': 'None'},
          {'name': 'season_number', 'wire': 'seasonNumber', 'type': 'int', 'default': 'None'},
          {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': '""'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode', 'wire': 'includeEpisode', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'List series history. Query params: event_type.',
 },
 {'name': 'sonarr_list_history_since',
  'method': 'GET',
  'path': '/api/v3/history/since',
  'pp': [],
  'qp': [
          {'name': 'date', 'wire': 'date', 'type': 'str', 'default': '""'},
          {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': '""'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode', 'wire': 'includeEpisode', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'List history since a date. Query params: date, event_type.',
 },
 {'name': 'sonarr_list_importlist',
  'method': 'GET',
  'path': '/api/v3/importlist',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import lists.',
 },
 {'name': 'sonarr_create_importlist',
  'method': 'POST',
  'path': '/api/v3/importlist',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create import lists. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_importlist_action',
  'method': 'POST',
  'path': '/api/v3/importlist/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create importlist action. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_importlist_bulk',
  'method': 'DELETE',
  'path': '/api/v3/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete importlist bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_update_importlist_bulk',
  'method': 'PUT',
  'path': '/api/v3/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update importlist bulk. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_importlist_schema',
  'method': 'GET',
  'path': '/api/v3/importlist/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the import lists schema (available fields/options).',
 },
 {'name': 'sonarr_create_importlist_test',
  'method': 'POST',
  'path': '/api/v3/importlist/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create importlist test. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_importlist_testall',
  'method': 'POST',
  'path': '/api/v3/importlist/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create importlist testall. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_importlist',
  'method': 'DELETE',
  'path': '/api/v3/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete import lists. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_importlist',
  'method': 'GET',
  'path': '/api/v3/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import lists by id.',
 },
 {'name': 'sonarr_update_importlist',
  'method': 'PUT',
  'path': '/api/v3/importlist/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Update import lists. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_importlistexclusion',
  'method': 'GET',
  'path': '/api/v3/importlistexclusion',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List import list exclusions.',
 },
 {'name': 'sonarr_create_importlistexclusion',
  'method': 'POST',
  'path': '/api/v3/importlistexclusion',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create import list exclusions. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_importlistexclusion_bulk',
  'method': 'DELETE',
  'path': '/api/v3/importlistexclusion/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete importlistexclusion bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_list_importlistexclusion_paged',
  'method': 'GET',
  'path': '/api/v3/importlistexclusion/paged',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
         ],
  'bk': 'none',
  'doc': 'List importlistexclusion paged. Query params: sort_key, sort_direction.',
 },
 {'name': 'sonarr_delete_importlistexclusion',
  'method': 'DELETE',
  'path': '/api/v3/importlistexclusion/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete import list exclusions. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_importlistexclusion',
  'method': 'GET',
  'path': '/api/v3/importlistexclusion/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single import list exclusions by id.',
 },
 {'name': 'sonarr_update_importlistexclusion',
  'method': 'PUT',
  'path': '/api/v3/importlistexclusion/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update import list exclusions. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_indexer',
  'method': 'GET',
  'path': '/api/v3/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexers.',
 },
 {'name': 'sonarr_create_indexer',
  'method': 'POST',
  'path': '/api/v3/indexer',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create indexers. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_indexer_action',
  'method': 'POST',
  'path': '/api/v3/indexer/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create indexer action. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_indexer_bulk',
  'method': 'DELETE',
  'path': '/api/v3/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete indexer bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_update_indexer_bulk',
  'method': 'PUT',
  'path': '/api/v3/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update indexer bulk. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_indexer_schema',
  'method': 'GET',
  'path': '/api/v3/indexer/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the indexers schema (available fields/options).',
 },
 {'name': 'sonarr_create_indexer_test',
  'method': 'POST',
  'path': '/api/v3/indexer/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create indexer test. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_indexer_testall',
  'method': 'POST',
  'path': '/api/v3/indexer/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create indexer testall. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_indexer',
  'method': 'DELETE',
  'path': '/api/v3/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete indexers. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_indexer',
  'method': 'GET',
  'path': '/api/v3/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single indexers by id.',
 },
 {'name': 'sonarr_update_indexer',
  'method': 'PUT',
  'path': '/api/v3/indexer/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Update indexers. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_indexerflag',
  'method': 'GET',
  'path': '/api/v3/indexerflag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexer flags.',
 },
 {'name': 'sonarr_list_language',
  'method': 'GET',
  'path': '/api/v3/language',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List languages.',
 },
 {'name': 'sonarr_get_language',
  'method': 'GET',
  'path': '/api/v3/language/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single languages by id.',
 },
 {'name': 'sonarr_list_languageprofile',
  'method': 'GET',
  'path': '/api/v3/languageprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List language profiles.',
 },
 {'name': 'sonarr_create_languageprofile',
  'method': 'POST',
  'path': '/api/v3/languageprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create language profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_languageprofile_schema',
  'method': 'GET',
  'path': '/api/v3/languageprofile/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the language profiles schema (available fields/options).',
 },
 {'name': 'sonarr_delete_languageprofile',
  'method': 'DELETE',
  'path': '/api/v3/languageprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete language profiles. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_languageprofile',
  'method': 'GET',
  'path': '/api/v3/languageprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single language profiles by id.',
 },
 {'name': 'sonarr_update_languageprofile',
  'method': 'PUT',
  'path': '/api/v3/languageprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update language profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_localization',
  'method': 'GET',
  'path': '/api/v3/localization',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List localization strings.',
 },
 {'name': 'sonarr_get_localization_language',
  'method': 'GET',
  'path': '/api/v3/localization/language',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List localization languages.',
 },
 {'name': 'sonarr_get_localization',
  'method': 'GET',
  'path': '/api/v3/localization/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single localization strings by id.',
 },
 {'name': 'sonarr_list_log',
  'method': 'GET',
  'path': '/api/v3/log',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
          {'name': 'level', 'wire': 'level', 'type': 'str', 'default': '""'},
         ],
  'bk': 'none',
  'doc': 'List server logs. Query params: sort_key, sort_direction, level.',
 },
 {'name': 'sonarr_list_log_file',
  'method': 'GET',
  'path': '/api/v3/log/file',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List log files.',
 },
 {'name': 'sonarr_list_log_file_update',
  'method': 'GET',
  'path': '/api/v3/log/file/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List update log files.',
 },
 {'name': 'sonarr_list_manualimport',
  'method': 'GET',
  'path': '/api/v3/manualimport',
  'pp': [],
  'qp': [
          {'name': 'folder', 'wire': 'folder', 'type': 'str', 'default': '""'},
          {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': '""'},
          {'name': 'series_id', 'wire': 'seriesId', 'type': 'int', 'default': 'None'},
          {'name': 'season_number', 'wire': 'seasonNumber', 'type': 'int', 'default': 'None'},
          {'name': 'filter_existing_files', 'wire': 'filterExistingFiles', 'type': 'bool', 'default': 'True'},
         ],
  'bk': 'none',
  'doc': 'List manual import candidates. Query params: folder, download_id.',
 },
 {'name': 'sonarr_commit_manual_import',
  'method': 'POST',
  'path': '/api/v3/manualimport',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Commit a manual import (body is a list of manual import items). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_metadata',
  'method': 'GET',
  'path': '/api/v3/metadata',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadata providers.',
 },
 {'name': 'sonarr_create_metadata',
  'method': 'POST',
  'path': '/api/v3/metadata',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create metadata providers. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_metadata_action',
  'method': 'POST',
  'path': '/api/v3/metadata/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create metadata action. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_metadata_schema',
  'method': 'GET',
  'path': '/api/v3/metadata/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the metadata providers schema (available fields/options).',
 },
 {'name': 'sonarr_create_metadata_test',
  'method': 'POST',
  'path': '/api/v3/metadata/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create metadata test. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_metadata_testall',
  'method': 'POST',
  'path': '/api/v3/metadata/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create metadata testall. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_metadata',
  'method': 'DELETE',
  'path': '/api/v3/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete metadata providers. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_metadata',
  'method': 'GET',
  'path': '/api/v3/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single metadata providers by id.',
 },
 {'name': 'sonarr_update_metadata',
  'method': 'PUT',
  'path': '/api/v3/metadata/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Update metadata providers. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_notification',
  'method': 'GET',
  'path': '/api/v3/notification',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List notification providers.',
 },
 {'name': 'sonarr_create_notification',
  'method': 'POST',
  'path': '/api/v3/notification',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create notification providers. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_notification_action',
  'method': 'POST',
  'path': '/api/v3/notification/action/{name}',
  'pp': [{'name': 'name', 'wire': 'name', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create notification action. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_notification_schema',
  'method': 'GET',
  'path': '/api/v3/notification/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the notification providers schema (available fields/options).',
 },
 {'name': 'sonarr_create_notification_test',
  'method': 'POST',
  'path': '/api/v3/notification/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Create notification test. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_create_notification_testall',
  'method': 'POST',
  'path': '/api/v3/notification/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create notification testall. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_notification',
  'method': 'DELETE',
  'path': '/api/v3/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete notification providers. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_notification',
  'method': 'GET',
  'path': '/api/v3/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single notification providers by id.',
 },
 {'name': 'sonarr_update_notification',
  'method': 'PUT',
  'path': '/api/v3/notification/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Update notification providers. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_parse',
  'method': 'GET',
  'path': '/api/v3/parse',
  'pp': [],
  'qp': [
          {'name': 'title', 'wire': 'title', 'type': 'str', 'default': '""'},
          {'name': 'path', 'wire': 'path', 'type': 'str', 'default': '""'},
         ],
  'bk': 'none',
  'doc': 'List title parsing results. Query params: title, path.',
 },
 {'name': 'sonarr_list_qualitydefinition',
  'method': 'GET',
  'path': '/api/v3/qualitydefinition',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List quality definitions.',
 },
 {'name': 'sonarr_get_qualitydefinition_limits',
  'method': 'GET',
  'path': '/api/v3/qualitydefinition/limits',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List qualitydefinition limits.',
 },
 {'name': 'sonarr_update_quality_definitions',
  'method': 'PUT',
  'path': '/api/v3/qualitydefinition/update',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Update qualitydefinition update. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_qualitydefinition',
  'method': 'GET',
  'path': '/api/v3/qualitydefinition/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single quality definitions by id.',
 },
 {'name': 'sonarr_update_qualitydefinition',
  'method': 'PUT',
  'path': '/api/v3/qualitydefinition/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update quality definitions. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_qualityprofile',
  'method': 'GET',
  'path': '/api/v3/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List quality profiles.',
 },
 {'name': 'sonarr_create_qualityprofile',
  'method': 'POST',
  'path': '/api/v3/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create quality profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_qualityprofile_schema',
  'method': 'GET',
  'path': '/api/v3/qualityprofile/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Return the quality profiles schema (available fields/options).',
 },
 {'name': 'sonarr_delete_qualityprofile',
  'method': 'DELETE',
  'path': '/api/v3/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete quality profiles. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_qualityprofile',
  'method': 'GET',
  'path': '/api/v3/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single quality profiles by id.',
 },
 {'name': 'sonarr_update_qualityprofile',
  'method': 'PUT',
  'path': '/api/v3/qualityprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update quality profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_queue',
  'method': 'GET',
  'path': '/api/v3/queue',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
          {'name': 'include_unknown_series_items', 'wire': 'includeUnknownSeriesItems', 'type': 'bool', 'default': 'False'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode', 'wire': 'includeEpisode', 'type': 'bool', 'default': 'False'},
          {'name': 'series_ids', 'wire': 'seriesIds', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'protocol', 'wire': 'protocol', 'type': 'str', 'default': '""'},
          {'name': 'languages', 'wire': 'languages', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'quality', 'wire': 'quality', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'status', 'wire': 'status', 'type': 'list[Any]', 'default': 'None'},
         ],
  'bk': 'none',
  'doc': 'List download client queue items. Query params: sort_key, sort_direction, protocol.',
 },
 {'name': 'sonarr_bulk_delete_queue',
  'method': 'DELETE',
  'path': '/api/v3/queue/bulk',
  'pp': [],
  'qp': [
          {'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': 'True'},
          {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': 'False'},
          {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': 'False'},
          {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Delete queue bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_queue_details',
  'method': 'GET',
  'path': '/api/v3/queue/details',
  'pp': [],
  'qp': [
          {'name': 'series_id', 'wire': 'seriesId', 'type': 'int', 'default': 'None'},
          {'name': 'episode_ids', 'wire': 'episodeIds', 'type': 'list[Any]', 'default': 'None'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode', 'wire': 'includeEpisode', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'List queue details.',
 },
 {'name': 'sonarr_grab_queue_bulk',
  'method': 'POST',
  'path': '/api/v3/queue/grab/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Grab multiple queued items now (body is a list of ids). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_grab_queue_item',
  'method': 'POST',
  'path': '/api/v3/queue/grab/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Grab the queued item now (forces the download client to fetch it). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_queue_status',
  'method': 'GET',
  'path': '/api/v3/queue/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List queue status.',
 },
 {'name': 'sonarr_delete_queue',
  'method': 'DELETE',
  'path': '/api/v3/queue/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': 'True'},
          {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': 'False'},
          {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': 'False'},
          {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'Delete download client queue items. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_list_release',
  'method': 'GET',
  'path': '/api/v3/release',
  'pp': [],
  'qp': [
          {'name': 'series_id', 'wire': 'seriesId', 'type': 'int', 'default': 'None'},
          {'name': 'episode_id', 'wire': 'episodeId', 'type': 'int', 'default': 'None'},
          {'name': 'season_number', 'wire': 'seasonNumber', 'type': 'int', 'default': 'None'},
         ],
  'bk': 'none',
  'doc': 'List release.',
 },
 {'name': 'sonarr_search_releases',
  'method': 'POST',
  'path': '/api/v3/release',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Search for releases for a series/episode (body carries seriesId/episodeId and other options). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_push_release',
  'method': 'POST',
  'path': '/api/v3/release/push',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Push a release to the download client. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_releaseprofile',
  'method': 'GET',
  'path': '/api/v3/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List release profiles.',
 },
 {'name': 'sonarr_create_releaseprofile',
  'method': 'POST',
  'path': '/api/v3/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create release profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_releaseprofile',
  'method': 'DELETE',
  'path': '/api/v3/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete release profiles. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_releaseprofile',
  'method': 'GET',
  'path': '/api/v3/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single release profiles by id.',
 },
 {'name': 'sonarr_update_releaseprofile',
  'method': 'PUT',
  'path': '/api/v3/releaseprofile/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update release profiles. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_remotepathmapping',
  'method': 'GET',
  'path': '/api/v3/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List remote path mappings.',
 },
 {'name': 'sonarr_create_remotepathmapping',
  'method': 'POST',
  'path': '/api/v3/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create remote path mappings. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_remotepathmapping',
  'method': 'DELETE',
  'path': '/api/v3/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete remote path mappings. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_remotepathmapping',
  'method': 'GET',
  'path': '/api/v3/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single remote path mappings by id.',
 },
 {'name': 'sonarr_update_remotepathmapping',
  'method': 'PUT',
  'path': '/api/v3/remotepathmapping/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update remote path mappings. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_rename',
  'method': 'GET',
  'path': '/api/v3/rename',
  'pp': [],
  'qp': [
          {'name': 'series_id', 'wire': 'seriesId', 'type': 'int', 'default': 'None'},
          {'name': 'season_number', 'wire': 'seasonNumber', 'type': 'int', 'default': 'None'},
         ],
  'bk': 'none',
  'doc': 'List rename.',
 },
 {'name': 'sonarr_list_rootfolder',
  'method': 'GET',
  'path': '/api/v3/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List root folders.',
 },
 {'name': 'sonarr_create_rootfolder',
  'method': 'POST',
  'path': '/api/v3/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create root folders. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_rootfolder',
  'method': 'DELETE',
  'path': '/api/v3/rootfolder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete root folders. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_rootfolder',
  'method': 'GET',
  'path': '/api/v3/rootfolder/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single root folders by id.',
 },
 {'name': 'sonarr_update_season_pass',
  'method': 'POST',
  'path': '/api/v3/seasonpass',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Apply season pass monitoring settings (body is a SeasonPassResource). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_series',
  'method': 'GET',
  'path': '/api/v3/series',
  'pp': [],
  'qp': [
          {'name': 'tvdb_id', 'wire': 'tvdbId', 'type': 'int', 'default': 'None'},
          {'name': 'include_season_images', 'wire': 'includeSeasonImages', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'List series.',
 },
 {'name': 'sonarr_add_series',
  'method': 'POST',
  'path': '/api/v3/series',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add a series to Sonarr (body is a SeriesResource). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_bulk_delete_series',
  'method': 'DELETE',
  'path': '/api/v3/series/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Delete series editor. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_bulk_update_series',
  'method': 'PUT',
  'path': '/api/v3/series/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update series editor. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_import_series',
  'method': 'POST',
  'path': '/api/v3/series/import',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Import series (body is a list of series resources). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_lookup_series',
  'method': 'GET',
  'path': '/api/v3/series/lookup',
  'pp': [],
  'qp': [
          {'name': 'term', 'wire': 'term', 'type': 'str', 'default': '""'},
         ],
  'bk': 'none',
  'doc': 'Search for a series by title (term), returning metadata candidates from TVDB.',
 },
 {'name': 'sonarr_delete_series',
  'method': 'DELETE',
  'path': '/api/v3/series/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'delete_files', 'wire': 'deleteFiles', 'type': 'bool', 'default': 'False'},
          {'name': 'add_import_list_exclusion', 'wire': 'addImportListExclusion', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'Delete series. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_series',
  'method': 'GET',
  'path': '/api/v3/series/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [
          {'name': 'include_season_images', 'wire': 'includeSeasonImages', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'none',
  'doc': 'Fetch a single series by id.',
 },
 {'name': 'sonarr_update_series',
  'method': 'PUT',
  'path': '/api/v3/series/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [
          {'name': 'move_files', 'wire': 'moveFiles', 'type': 'bool', 'default': 'False'},
         ],
  'bk': 'dict',
  'doc': 'Update series. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_series_folder',
  'method': 'GET',
  'path': '/api/v3/series/{id}/folder',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single series by id.',
 },
 {'name': 'sonarr_list_system_backup',
  'method': 'GET',
  'path': '/api/v3/system/backup',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system backups.',
 },
 {'name': 'sonarr_restore_backup_upload',
  'method': 'POST',
  'path': '/api/v3/system/backup/restore/upload',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Restore Sonarr from an uploaded backup file (multipart upload - limited support). WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_restore_backup',
  'method': 'POST',
  'path': '/api/v3/system/backup/restore/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Restore Sonarr from a backup. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_delete_system_backup',
  'method': 'DELETE',
  'path': '/api/v3/system/backup/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete system backups. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_restart_sonarr',
  'method': 'POST',
  'path': '/api/v3/system/restart',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Restart the Sonarr service. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_system_routes',
  'method': 'GET',
  'path': '/api/v3/system/routes',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List registered API routes.',
 },
 {'name': 'sonarr_get_system_routes_duplicate',
  'method': 'GET',
  'path': '/api/v3/system/routes/duplicate',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List duplicate registered API routes.',
 },
 {'name': 'sonarr_shutdown_sonarr',
  'method': 'POST',
  'path': '/api/v3/system/shutdown',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Shut down the Sonarr service. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_get_system_status',
  'method': 'GET',
  'path': '/api/v3/system/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system status.',
 },
 {'name': 'sonarr_get_system_task',
  'method': 'GET',
  'path': '/api/v3/system/task',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List scheduled tasks.',
 },
 {'name': 'sonarr_get_system_task_by_id',
  'method': 'GET',
  'path': '/api/v3/system/task/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single scheduled tasks by id.',
 },
 {'name': 'sonarr_list_tag',
  'method': 'GET',
  'path': '/api/v3/tag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List tags.',
 },
 {'name': 'sonarr_create_tag',
  'method': 'POST',
  'path': '/api/v3/tag',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create tags. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_tag_detail',
  'method': 'GET',
  'path': '/api/v3/tag/detail',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List tag details.',
 },
 {'name': 'sonarr_get_tag_detail',
  'method': 'GET',
  'path': '/api/v3/tag/detail/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single tag details by id.',
 },
 {'name': 'sonarr_delete_tag',
  'method': 'DELETE',
  'path': '/api/v3/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete tags. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'sonarr_get_tag',
  'method': 'GET',
  'path': '/api/v3/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single tags by id.',
 },
 {'name': 'sonarr_update_tag',
  'method': 'PUT',
  'path': '/api/v3/tag/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'str'}],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update tags. WRITE: this modifies your Sonarr instance.',
 },
 {'name': 'sonarr_list_update',
  'method': 'GET',
  'path': '/api/v3/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List available updates.',
 },
 {'name': 'sonarr_list_wanted_cutoff',
  'method': 'GET',
  'path': '/api/v3/wanted/cutoff',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_episode_file', 'wire': 'includeEpisodeFile', 'type': 'bool', 'default': 'False'},
          {'name': 'include_images', 'wire': 'includeImages', 'type': 'bool', 'default': 'False'},
          {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': 'True'},
         ],
  'bk': 'none',
  'doc': 'List cutoff. Query params: sort_key, sort_direction.',
 },
 {'name': 'sonarr_get_wanted_cutoff',
  'method': 'GET',
  'path': '/api/v3/wanted/cutoff/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single cutoff by id.',
 },
 {'name': 'sonarr_list_wanted_missing',
  'method': 'GET',
  'path': '/api/v3/wanted/missing',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': '1'},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': '10'},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': '""'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': '""'},
          {'name': 'include_series', 'wire': 'includeSeries', 'type': 'bool', 'default': 'False'},
          {'name': 'include_images', 'wire': 'includeImages', 'type': 'bool', 'default': 'False'},
          {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': 'True'},
         ],
  'bk': 'none',
  'doc': 'List missing. Query params: sort_key, sort_direction.',
 },
 {'name': 'sonarr_get_wanted_missing',
  'method': 'GET',
  'path': '/api/v3/wanted/missing/{id}',
  'pp': [{'name': 'id', 'wire': 'id', 'type': 'int'}],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single missing by id.',
 },
 {'name': 'sonarr_ping',
  'method': 'GET',
  'path': '/ping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Ping the server to verify it is reachable and authenticated.',
 },]


def _tool_source(spec: dict[str, Any]) -> str:
    parts: list[str] = []
    for p in spec["pp"]:
        parts.append(f"{p['name']}: {p['type']}")
    for q in spec["qp"]:
        parts.append(f"{q['name']}: {q['type']} = {q['default']}")
    if spec["bk"] == "dict":
        parts.append("body: dict[str, Any] = {}")
    elif spec["bk"] == "list":
        parts.append("body: list[Any] = []")
    sig = ", ".join(parts)

    path_tmpl = spec["path"]
    for p in spec["pp"]:
        path_tmpl = path_tmpl.replace("{" + p["wire"] + "}", "{" + p["name"] + "}")
    if spec["pp"]:
        arg_call = ", ".join(f"{p['name']}=quote(str({p['name']}))" for p in spec["pp"])
        url_expr = f'f"{path_tmpl}".format({arg_call})'
    else:
        url_expr = repr(spec["path"])

    if spec["qp"]:
        params_expr = "_omit({" + ", ".join(f'"{q["wire"]}": {q["name"]}' for q in spec["qp"]) + "})"
    else:
        params_expr = "None"
    json_expr = "body" if spec["bk"] != "none" else "None"

    doc = spec["doc"].replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return (
        f"async def {spec['name']}({sig}) -> JSONVal:\n"
        f'    """{doc}"""\n'
        f"    return await _req({spec['method']!r}, {url_expr}, params={params_expr}, json_body={json_expr})\n"
    )


def _op_line(name: str, fn: Any) -> str:
    """One line of a group tool's description: signature + one-line doc."""
    sig = ", ".join(
        p.name if p.default is inspect.Parameter.empty else f"{p.name}={p.default!r}"
        for p in inspect.signature(fn).parameters.values()
    )
    return f"- {name}({sig}) — {' '.join((fn.__doc__ or '').split())}"


def _register_group(group: str, names: tuple[str, ...], ns: dict[str, Any], method_of: dict[str, str]) -> None:
    """Register one dispatching tool that fans out to every endpoint function
    named in `names`. The endpoint functions themselves are untouched -
    they're just looked up by name instead of each becoming its own tool."""
    fns = {n: ns[n] for n in names}

    async def dispatch(operation: str, arguments: JSONObj | None = None) -> JSONVal:
        fn = fns.get(operation)
        if fn is None:
            raise ToolError(f"Unknown operation {operation!r} for {group}. Valid: {', '.join(fns)}")
        return await fn(**(arguments or {}))

    dispatch.__annotations__["operation"] = Literal[names]
    ann = READONLY if {method_of[n] for n in names} == {"GET"} else None
    mcp.add_tool(
        Tool.from_function(
            dispatch,
            name=group,
            description=(
                f"{group.replace('_', ' ')} operations on Sonarr. Pass `operation` and an "
                f"`arguments` dict matching that operation's parameters.\n\n"
                + "\n".join(_op_line(n, f) for n, f in fns.items())
            ),
            annotations=ann,
        )
    )


def register_tools() -> None:
    src = "\n".join(_tool_source(spec) for spec in _TOOL_REGISTRY)
    ns: dict[str, Any] = {}
    exec(src, globals(), ns)
    method_of = {spec["name"]: spec["method"] for spec in _TOOL_REGISTRY}
    for group, names in _GROUPS.items():
        _register_group(group, names, ns, method_of)


register_tools()


def main() -> None:
    global _client
    url = os.environ.get("SONARR_URL")
    if not url:
        print("SONARR_URL environment variable is required (e.g. http://sonarr.example.com)", file=sys.stderr)
        raise SystemExit(1)
    _client = build_client(url, os.environ.get("SONARR_API_KEY"))
    mcp.run()


if __name__ == "__main__":
    main()
